### ISSUE TITLE
ECMASyntaxError on /regexp/ following }

### ISSUE THREAD

**Issue by Gallaecio** [calmjs/calmjs.parse#25]
```python
>>> es5('if (a) { do_something(); }\n/checkbox/.test(a)')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adrian/temporal/venv/lib/python3.6/site-packages/calmjs/parse/factory.py", line 79, in parse
    return f(source, *a, **kw)
  File "/home/adrian/temporal/venv/lib/python3.6/site-packages/calmjs/parse/parsers/es5.py", line 1474, in parse
    return parser.parse(source)
  File "/home/adrian/temporal/venv/lib/python3.6/site-packages/calmjs/parse/parsers/es5.py", line 115, in parse
    tracking=self.yacc_tracking)
  File "/home/adrian/temporal/venv/lib/python3.6/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt(input, lexer, debug, tracking, tokenfunc)
  File "/home/adrian/temporal/venv/lib/python3.6/site-packages/ply/yacc.py", line 909, in parseopt
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/adrian/temporal/venv/lib/python3.6/site-packages/ply/yacc.py", line 192, in call_errorfunc
    r = errorfunc(token)
  File "/home/adrian/temporal/venv/lib/python3.6/site-packages/calmjs/parse/parsers/es5.py", line 127, in p_error
    self._raise_syntax_error(token)
  File "/home/adrian/temporal/venv/lib/python3.6/site-packages/calmjs/parse/parsers/es5.py", line 105, in _raise_syntax_error
    raise ECMASyntaxError(msg[len(tokens)].format(*tokens))
calmjs.parse.exceptions.ECMASyntaxError: Unexpected '/' at 2:1 after '\n' at 1:27
```

**Comment by metatoaster** [comment]
Thank you for your report.  I can fully confirm this, along with a number of related syntax (as per [this StackOverflow thread](https://stackoverflow.com/questions/5519596/when-parsing-javascript-what-determines-the-meaning-of-a-slash)), being an issue with the lexer on its own not being able to disambiguate whether the `/` is a start of `REGEX` token or simply a `DIV` token from just dealing with tokens.  The fix is coming, it will involve a way for the parser to communicate whether the `DIV` token is disallowed (perhaps vice versa, to be confirmed).  This fix is in the works, but additional work will be needed to try to find as many pathological failure cases relating to this as possible.

At first glance this lexing issue does not appear to affect slimit, but if the newline `\n` is removed the same issue will manifest there, while node will still happily parse the resulting single line without any issues.  A previous fix to `calmjs.parse` was made to ensure that newline tokens (amongst others) are not matched for that regex token permission check essentially cause that existing bug to always manifest here.

**Comment by metatoaster** [comment]
Also released as `calmjs.parse-1.2.1`.

**Comment by Gallaecio** [comment]
Wow, that was quick! :eyes:
