### ISSUE TITLE
Issue while parsing code

### ISSUE THREAD

**Issue by r0oth3x49** [calmjs/calmjs.parse#40]
first of all thank you so much for creating such a great project I 'm facing an issue while trying to parse the attach js code. it throws an NoneType Exception, the js code is attached below.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\__init__.py", line 18, in parse
    xml = _visitor.visit(tree)
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\xmlvisitor.py", line 25, in visit
    return getattr(self, method, self.generic_visit)(node)
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\xmlvisitor.py", line 33, in visit_ES5Program
    program.extend(self.visit(child))
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\xmlvisitor.py", line 25, in visit
    return getattr(self, method, self.generic_visit)(node)
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\xmlvisitor.py", line 218, in visit_ExprStatement
    return self.visit(node.expr)
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\xmlvisitor.py", line 25, in visit
    return getattr(self, method, self.generic_visit)(node)
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\xmlvisitor.py", line 434, in visit_FunctionCall
    arguments.extend(self.visit(arg))
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\xmlvisitor.py", line 25, in visit
    return getattr(self, method, self.generic_visit)(node)
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\xmlvisitor.py", line 456, in visit_Array
    array.extend(self.visit(item))
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\xmlvisitor.py", line 25, in visit
    return getattr(self, method, self.generic_visit)(node)
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\xmlvisitor.py", line 446, in visit_Object
    obj.extend(self.visit(prop))
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\xmlvisitor.py", line 25, in visit
    return getattr(self, method, self.generic_visit)(node)
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\xmlvisitor.py", line 81, in visit_Assign
    propel.extend(self.visit(node.right))
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\xmlvisitor.py", line 25, in visit
    return getattr(self, method, self.generic_visit)(node)
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\xmlvisitor.py", line 377, in visit_FuncExpr
    body.extend(self.visit(element))
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\xmlvisitor.py", line 25, in visit
    return getattr(self, method, self.generic_visit)(node)
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\xmlvisitor.py", line 218, in visit_ExprStatement
    return self.visit(node.expr)
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\xmlvisitor.py", line 25, in visit
    return getattr(self, method, self.generic_visit)(node)
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\xmlvisitor.py", line 88, in visit_Assign
    right.extend(self.visit(node.right))
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\xmlvisitor.py", line 25, in visit
    return getattr(self, method, self.generic_visit)(node)
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\xmlvisitor.py", line 377, in visit_FuncExpr
    body.extend(self.visit(element))
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\xmlvisitor.py", line 25, in visit
    return getattr(self, method, self.generic_visit)(node)
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\xmlvisitor.py", line 299, in visit_Switch
    switch.extend(self.visit(child))
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\xmlvisitor.py", line 25, in visit
    return getattr(self, method, self.generic_visit)(node)
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\xmlvisitor.py", line 314, in visit_Default
    default.extend(self.visit(element))
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\xmlvisitor.py", line 25, in visit
    return getattr(self, method, self.generic_visit)(node)
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\xmlvisitor.py", line 319, in visit_Throw
    throwel.extend(self.visit(node.expr))
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\xmlvisitor.py", line 25, in visit
    return getattr(self, method, self.generic_visit)(node)
  File "E:\r0ot_h3x49\dev\local\hackit\hsenv\lib\site-packages\js2xml\xmlvisitor.py", line 405, in visit_NewExpr
    for arg in node.args:
TypeError: 'NoneType' object is not iterable
```
[code.txt](https://github.com/calmjs/calmjs.parse/files/7152305/code.txt)

**Code which i 'm trying to parse with**
```python
>> import js2xml
>> data = open("code.txt", "r").read()
>> p = js2xml.parse(data)
```

**Comment by metatoaster** [comment]
@r0oth3x49 The input that triggers this particular issue you found in js2xml is specifically this particular node from the input.

```
<NewExpr @1766:31 args=None, identifier=<Identifier @1766:35 value='Error'>>
```

Which translates into

```js
new Error
```

~~You may wish to file an issue at the issue tracker for js2xml~~ (I just noted that you have already closed this issue and in fact filed scrapinghub/js2xml#53). It would be best to reduce the problem to the following minimum code required to reproduce the actual error (without forcing the library maintainers from having to spend time to locate the actual problematic input inside the 5385 lines of code provided):

```pycon
>>> import js2xml
>>> p = js2xml.parse('new Error')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/env/lib/python3.9/site-packages/js2xml/__init__.py", line 18, in parse
    xml = _visitor.visit(tree)
...
  File "/tmp/env/lib/python3.9/site-packages/js2xml/xmlvisitor.py", line 402, in visit_NewExpr
    for arg in node.args:
TypeError: 'NoneType' object is not iterable
>>> 
```

The behavior of this attribute is intended, as there needs to be a way to disambiguate `new Error` and `new Error()`, and thus a lack of arguments will simply result in `None`, and the latter code with an empty set of arguments will be reflected as such, i.e.

```pycon
>>> es5('new Error').children()[0].expr
<NewExpr @1:1 args=None, identifier=<Identifier @1:5 value='Error'>>
>>> es5('new Error()').children()[0].expr
<NewExpr @1:1 args=<Arguments @1:10 items=[
  
]>, identifier=<Identifier @1:5 value='Error'>>
>>> 
```

**Comment by r0oth3x49** [comment]
@metatoaster thank you so much for swift response, i have updated the issue on js2xml. and tried to fix the issue with if condition which is not correct as you already explained that it is intended behavior. but this can be handled properly i guess instead of code break.
